name: Flext
favicon: null
layout_spectrum: 0.8186619197949767
typography_spectrum: 0.5007649068720639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9810200531501323
  lightness: 0.8935021450743079
  saturation: 0.9604379928205162
  rhythmicContrast: 0.8701038772705942
purpose: []
